---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 735477897322987520-VFSVA0SpvUwjIYnZzrFYyXCNspkEkuZ
:access_token_secret: j7DaTLx03rIZ4sihmCxZ2gBlpnbSXDpdFAUnOhytwGzVP
